Users
InnoSWP/InnoCart-04 pull request #28
Opened 2022-06-08 17:29 UTC by Tyu-cr

2022-06-10 06:04 UTC, ruca905 requested changes

2022-06-10 06:04 UTC, ruca905 commented on backend/users/views.py
> +def register(request, format=None):
I think, that is obvious that only register app in our backend can trigger this endpoint (creation of new user == register new user). So we should somehow forbid this action for all users except register module. But for now this is not a big problem, security is out of MVP, so if you dont know how to do it, you can create an issue with low priority and forget about this problem for some time

2022-06-10 06:04 UTC, ruca905 commented on backend/users/models.py
> +    phoneNumber = models.IntegerField(null=False, blank=False)
I think, we should make phone number string typed. Now, i`ll update the openapi branch, pull it to get this change

2022-06-10 14:25 UTC, Tyu-cr commented on backend/users/serializers.py
> +    userId = serializers.IntegerField()
first id - number of row in db
second id - user id

2022-06-10 15:54 UTC, ruca905 commented on backend/users/serializers.py
> +    userId = serializers.IntegerField()
These are the same entities

2022-06-11 12:18 UTC, ruca905 submitted a review, later dismissed

2022-06-17 14:27 UTC, ruca905 approved these changes

2022-06-17 14:28 UTC, merged